name: Java CI/CD

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    name: Build, Test, and Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Adjust to your desired Java version

      - name: Build with Maven
        run: mvn clean install
        working-directory: ./path/to/your/java/project  # Replace with the path to your Java project

      - name: Run Tests
        run: mvn test
        working-directory: ./path/to/your/java/project  # Replace with the path to your Java project

      - name: Package
        run: mvn package
        working-directory: ./path/to/your/java/project  # Replace with the path to your Java project

      # Optionally, you can upload the built JAR file as an artifact
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: ./path/to/your/java/project/target/your-app.jar  # Replace with the path to your JAR file
